var data = [{
        UnitName: 'A01E02',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'A01',
        StationName: 'Metro Center, G and 11th St Entrance',
        LocationDescription: 'Escalator between street and mezzanine',
        SymptomCode: null,
        TimeOutOfService: '1111',
        SymptomDescription: 'Service Call',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T11:11:00',
        DateUpdated: '2019-07-15T11:12:06',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'A02E04',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'A02',
        StationName: 'Farragut North, L Street Entrance, East of Connecticut, north side L Street',
        LocationDescription: 'Escalator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '0647',
        SymptomDescription: 'Other',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-12T06:47:00',
        DateUpdated: '2019-07-14T12:59:28',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'A07X02',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'A07',
        StationName: 'Tenleytown-AU',
        LocationDescription: 'Escalator between street and middle landing, east side of Wisconsin Avenue',
        SymptomCode: null,
        TimeOutOfService: '0256',
        SymptomDescription: 'Major Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-10T02:56:00',
        DateUpdated: '2019-07-15T13:26:28',
        EstimatedReturnToService: '2019-07-15T23:59:59'
      },
      {
        UnitName: 'A08N03',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'A08',
        StationName: 'Friendship Heights, Western Avenue Entrance',
        LocationDescription: 'Escalator between middle landing and mezzanine',
        SymptomCode: null,
        TimeOutOfService: '1112',
        SymptomDescription: 'Minor Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T11:12:00',
        DateUpdated: '2019-07-15T11:21:54',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'B01W01',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'B01',
        StationName: 'Gallery Pl-Chinatown, 9th and G Street Entrance',
        LocationDescription: 'Escalator between street and mezzanine',
        SymptomCode: null,
        TimeOutOfService: '0530',
        SymptomDescription: 'Inspection Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-12T05:30:00',
        DateUpdated: '2019-07-15T10:26:45',
        EstimatedReturnToService: '2019-07-19T23:59:59'
      },
      {
        UnitName: 'B01W05',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'B01',
        StationName: 'Gallery Pl-Chinatown, 9th and G Street Entrance',
        LocationDescription: 'Escalator between mezzanine and platform to Glenmont',
        SymptomCode: null,
        TimeOutOfService: '0857',
        SymptomDescription: 'Other',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-11T08:57:00',
        DateUpdated: '2019-07-14T12:22:51',
        EstimatedReturnToService: '2019-07-15T23:59:59'
      },
      {
        UnitName: 'B05X03',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'B05',
        StationName: 'Brookland-CUA',
        LocationDescription: 'Escalator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '1241',
        SymptomDescription: 'Service Call',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T12:41:00',
        DateUpdated: '2019-07-15T12:45:02',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'E06X05',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'B06',
        StationName: 'Fort Totten',
        LocationDescription: 'Escalator between mezzanine and lower platform for Green Line',
        SymptomCode: null,
        TimeOutOfService: '0357',
        SymptomDescription: 'Inspection Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-08T03:57:00',
        DateUpdated: '2019-07-14T13:00:27',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'B08S03',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'B08',
        StationName: 'Silver Spring, South Side/Bus Terminal Entrance',
        LocationDescription: 'Escalator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '0836',
        SymptomDescription: 'Preventive Maintenance Inspection',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T08:36:00',
        DateUpdated: '2019-07-15T08:38:00',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'B10X02',
        UnitType: 'ELEVATOR',
        UnitStatus: null,
        StationCode: 'B10',
        StationName: 'Wheaton',
        LocationDescription: 'Garage elevator',
        SymptomCode: null,
        TimeOutOfService: '0658',
        SymptomDescription: 'Modernization',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-11T06:58:00',
        DateUpdated: '2019-07-11T07:02:46',
        EstimatedReturnToService: '2020-01-04T23:59:59'
      },
      {
        UnitName: 'C02W02',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'C02',
        StationName: 'McPherson Square, Vermont Ave./Veterans Administration Entrance',
        LocationDescription: 'Escalator between street and mezzanine',
        SymptomCode: null,
        TimeOutOfService: '0551',
        SymptomDescription: 'Minor Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T05:51:00',
        DateUpdated: '2019-07-15T06:59:57',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'C02W03',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'C02',
        StationName: 'McPherson Square, Vermont Ave./Veterans Administration Entrance',
        LocationDescription: 'Escalator between street and mezzanine',
        SymptomCode: null,
        TimeOutOfService: '0050',
        SymptomDescription: 'Inspection Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-05T00:50:00',
        DateUpdated: '2019-07-15T09:02:34',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'C03E05',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'C03',
        StationName: 'Farragut West, 17th Street Entrance',
        LocationDescription: 'Escalator between mezzanine and platform to New Carrollton/Largo Town Center',
        SymptomCode: null,
        TimeOutOfService: '1909',
        SymptomDescription: 'Minor Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-12T19:09:00',
        DateUpdated: '2019-07-14T12:59:56',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'C06X05',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'C06',
        StationName: 'Arlington Cemetery',
        LocationDescription: 'Escalator between mezzanine and platform to Franconia-Springfield',
        SymptomCode: null,
        TimeOutOfService: '0107',
        SymptomDescription: 'Major Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-11T01:07:00',
        DateUpdated: '2019-07-15T12:46:43',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'C06X08',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'C06',
        StationName: 'Arlington Cemetery',
        LocationDescription: 'Escalator between mezzanine and platform to Franconia-Springfield',
        SymptomCode: null,
        TimeOutOfService: '0109',
        SymptomDescription: 'Minor Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-11T01:09:00',
        DateUpdated: '2019-07-15T10:02:42',
        EstimatedReturnToService: '2019-07-15T23:59:59'
      },
      {
        UnitName: 'C08X01',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'C08',
        StationName: 'Pentagon City',
        LocationDescription: 'Escalator between street and mezzanine on west side of Hayes street, at The Fashion Center',
        SymptomCode: null,
        TimeOutOfService: '0458',
        SymptomDescription: 'Major Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-11T04:58:00',
        DateUpdated: '2019-07-13T10:53:16',
        EstimatedReturnToService: '2019-07-15T23:59:59'
      },
      {
        UnitName: 'C10N04',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'C10',
        StationName: 'Ronald Reagan Washington National Airport, North Entrance',
        LocationDescription: 'Escalator between mezzanine and platform to Huntington/Franconia-Springfield',
        SymptomCode: null,
        TimeOutOfService: '0558',
        SymptomDescription: 'Minor Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T05:58:00',
        DateUpdated: '2019-07-15T12:15:23',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'D01X02',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'D01',
        StationName: 'Federal Triangle',
        LocationDescription: 'Escalator between street and middle landing',
        SymptomCode: null,
        TimeOutOfService: '1219',
        SymptomDescription: 'Service Call',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T12:19:00',
        DateUpdated: '2019-07-15T12:20:27',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'D05X03',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'D05',
        StationName: 'Capitol South',
        LocationDescription: 'Escalator between street and mezzanine',
        SymptomCode: null,
        TimeOutOfService: '1317',
        SymptomDescription: 'Service Call',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T13:17:00',
        DateUpdated: '2019-07-15T13:18:13',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'E01X07',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'E01',
        StationName: 'Mt Vernon Sq 7th St-Convention Center',
        LocationDescription: 'Escalator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '1151',
        SymptomDescription: 'Service Call',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T11:51:00',
        DateUpdated: '2019-07-15T11:56:40',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'E02N01',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'E02',
        StationName: 'Shaw-Howard U, 7th and S St. N.W. Entrance',
        LocationDescription: 'Escalator between street and mezzanine',
        SymptomCode: null,
        TimeOutOfService: '0416',
        SymptomDescription: 'Minor Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T04:16:00',
        DateUpdated: '2019-07-15T05:36:54',
        EstimatedReturnToService: '2019-07-17T23:59:59'
      },
      {
        UnitName: 'E02N02',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'E02',
        StationName: 'Shaw-Howard U, 7th and S St. N.W. Entrance',
        LocationDescription: 'Escalator between street and mezzanine',
        SymptomCode: null,
        TimeOutOfService: '0433',
        SymptomDescription: 'Inspection Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T04:33:00',
        DateUpdated: '2019-07-15T04:34:28',
        EstimatedReturnToService: '2019-07-22T23:59:59'
      },
      {
        UnitName: 'E09X04',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'E09',
        StationName: 'College Park-U of MD',
        LocationDescription: 'Escalator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '0440',
        SymptomDescription: 'Minor Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-11T04:40:00',
        DateUpdated: '2019-07-13T10:52:27',
        EstimatedReturnToService: '2019-07-15T23:59:59'
      },
      {
        UnitName: 'F01N02',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'F01',
        StationName: 'Gallery Pl-Chinatown, 7th and H Street/Chinatown Entrance',
        LocationDescription: 'Escalator between street and middle landing',
        SymptomCode: null,
        TimeOutOfService: '1018',
        SymptomDescription: 'Minor Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-13T10:18:00',
        DateUpdated: '2019-07-15T11:54:37',
        EstimatedReturnToService: '2019-07-15T23:59:59'
      },
      {
        UnitName: 'F02X03',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'F02',
        StationName: 'Archives-Navy Memorial-Penn Quarter',
        LocationDescription: 'Escalator between street and mezzanine',
        SymptomCode: null,
        TimeOutOfService: '0604',
        SymptomDescription: 'Modernization',
        DisplayOrder: 0,
        DateOutOfServ: '2019-05-29T06:04:00',
        DateUpdated: '2019-06-17T06:35:42',
        EstimatedReturnToService: '2019-09-13T23:59:59'
      },
      {
        UnitName: 'F03N06',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'F03',
        StationName: 'L\'Enfant Plaza, 7th St/Maryland Ave./Smithsonian Museums Entrance/VRE trains',
        LocationDescription: 'Escalator between mezzanine and platform to Greenbelt/Mr. Vernon Sq',
        SymptomCode: null,
        TimeOutOfService: '0437',
        SymptomDescription: 'Inspection Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-15T04:37:00',
        DateUpdated: '2019-07-15T13:23:16',
        EstimatedReturnToService: '2019-07-22T23:59:59'
      },
      {
        UnitName: 'F06S01',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'F06',
        StationName: 'Anacostia, Howard Road Entrance',
        LocationDescription: 'Escalator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '0702',
        SymptomDescription: 'Minor Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-13T07:02:00',
        DateUpdated: '2019-07-14T11:23:27',
        EstimatedReturnToService: '2019-07-15T23:59:59'
      },
      {
        UnitName: 'F06S02',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'F06',
        StationName: 'Anacostia, Howard Road Entrance',
        LocationDescription: 'Escalator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '0711',
        SymptomDescription: 'Minor Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-13T07:11:00',
        DateUpdated: '2019-07-14T11:27:24',
        EstimatedReturnToService: '2019-07-15T23:59:59'
      },
      {
        UnitName: 'F06S03',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'F06',
        StationName: 'Anacostia, Howard Road Entrance',
        LocationDescription: 'Escalator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '0400',
        SymptomDescription: 'Major Repair',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-04T04:00:00',
        DateUpdated: '2019-07-15T11:47:43',
        EstimatedReturnToService: '2019-07-15T23:59:59'
      },
      {
        UnitName: 'F07X06',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'F07',
        StationName: 'Congress Heights',
        LocationDescription: 'Escalator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '2359',
        SymptomDescription: 'Modernization',
        DisplayOrder: 0,
        DateOutOfServ: '2019-04-14T23:59:00',
        DateUpdated: '2019-04-26T04:11:34',
        EstimatedReturnToService: '2019-07-31T23:59:59'
      },
      {
        UnitName: 'F07X07',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'F07',
        StationName: 'Congress Heights',
        LocationDescription: 'Escalator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '0000',
        SymptomDescription: 'Modernization',
        DisplayOrder: 0,
        DateOutOfServ: '2019-04-15T00:00:00',
        DateUpdated: '2019-04-26T04:11:34',
        EstimatedReturnToService: '2019-07-31T23:59:59'
      },
      {
        UnitName: 'G04X02',
        UnitType: 'ELEVATOR',
        UnitStatus: null,
        StationCode: 'G04',
        StationName: 'Morgan Boulevard',
        LocationDescription: 'Elevator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '0221',
        SymptomDescription: 'Modernization',
        DisplayOrder: 0,
        DateOutOfServ: '2019-07-02T02:21:00',
        DateUpdated: '2019-07-04T06:33:53',
        EstimatedReturnToService: '2019-09-27T23:59:59'
      },
      {
        UnitName: 'G05X01',
        UnitType: 'ELEVATOR',
        UnitStatus: null,
        StationCode: 'G05',
        StationName: 'Largo Town Center',
        LocationDescription: 'Elevator between street and mezzanine',
        SymptomCode: null,
        TimeOutOfService: '0135',
        SymptomDescription: 'Modernization',
        DisplayOrder: 0,
        DateOutOfServ: '2019-04-09T01:35:00',
        DateUpdated: '2019-07-01T11:12:57',
        EstimatedReturnToService: '2019-07-31T23:59:59'
      },
      {
        UnitName: 'G05X03',
        UnitType: 'ELEVATOR',
        UnitStatus: null,
        StationCode: 'G05',
        StationName: 'Largo Town Center',
        LocationDescription: 'Elevator between mezzanine and platform',
        SymptomCode: null,
        TimeOutOfService: '0146',
        SymptomDescription: 'Modernization',
        DisplayOrder: 0,
        DateOutOfServ: '2019-04-09T01:46:00',
        DateUpdated: '2019-07-02T08:56:43',
        EstimatedReturnToService: '2019-07-16T23:59:59'
      },
      {
        UnitName: 'K01X02',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'K01',
        StationName: 'Court House',
        LocationDescription: 'Escalator between street (Wilson Blvd) and middle landing/tunnel',
        SymptomCode: null,
        TimeOutOfService: '1750',
        SymptomDescription: 'Modernization',
        DisplayOrder: 0,
        DateOutOfServ: '2018-11-05T17:50:00',
        DateUpdated: '2019-07-02T14:33:48',
        EstimatedReturnToService: '2019-12-31T23:59:59'
      },
      {
        UnitName: 'K01X05',
        UnitType: 'ESCALATOR',
        UnitStatus: null,
        StationCode: 'K01',
        StationName: 'Court House',
        LocationDescription: 'Escalator between middle landing and mezzanine',
        SymptomCode: null,
        TimeOutOfService: '0402',
        SymptomDescription: 'Modernization',
        DisplayOrder: 0,
        DateOutOfServ: '2019-03-15T04:02:00',
        DateUpdated: '2019-07-02T13:59:45',
        EstimatedReturnToService: '2019-07-29T23:59:59'
      }
    ]